'use client';
import { useMemo, useState } from 'react';

const activities=[['christ','Christ by train','Iconic first-time Rio view','santa'],['sugar','Sugarloaf at sunset','Cable car + bay panorama','copa'],['beach','Ipanema / beach day','Easy, flexible beach time','copa'],['shopping','Mall shopping + luxury boutiques','Shopping Leblon, VillageMall and beach-neighborhood style','copa'],['samba','Samba + Santa Teresa','Music, food and cultural energy','santa'],['game','Maracanã game','Sunday’s fixed main event','santa'],['forest','Tijuca Forest','Nature and movement','barra'],['africa','Little Africa','Afro-Brazilian history and samba roots','santa']] as const;
const mapIds={santa:['harbourside','stpool','vintage'],copa:['rio001','adv001','panoramic'],barra:['pepe','castle','oasis']} as const;
const stays={santa:[['Harbourside 6-bedroom villa','Santa Teresa','Best overall for game day, Lapa and history.'],['Santa Teresa house with pool','Santa Teresa','Large-group base near Centro.'],['Vintage Chic Villa','Santa Teresa','Historic character and central access.']],copa:[['Rio001 beachfront penthouse','Copacabana','Best beach access with a lively base.'],['ADV001 oceanfront penthouse','Copacabana','Oceanfront pool and iconic location.'],['Copacabana Panoramic Penthouse','Copacabana','Classic Rio position and beach convenience.']],barra:[['Oceanfront penthouse with private pool','Barra / Praia do Pepe','Best secluded, celebrity-style beach feel.'],['A Castle in Rio — waterfall villa','Itanhangá','Best for a dramatic private escape.'],['Oasis in Freguesia','Freguesia','Best amenity value, with longer transfers.']]} as const;
const flightPlans={
 wed:{departure:'Wednesday, Sep 23',arrival:'Thursday, Sep 24 · 8:20 AM',feeder:'Use the supplied positioning plan',t1:'AA2887 · CLE 6:25 AM → MIA 9:20 AM',t2:'AA2638 · PUJ 12:02 PM → MIA 2:39 PM',t3:'Drive FLL area → MIA; arrive by 8:00 PM',shared:'AA905 · MIA → GIG overnight',summary:'This is the only option with the supplied, date-specific feeder plan. It gives the group Thursday to settle in before the weekend.'},
 thu:{departure:'Thursday, Sep 24',arrival:'Friday, Sep 25 · morning',feeder:'Re-price all three feeder trips for Thursday',t1:'CLE → MIA: choose a Thursday flight that arrives by 7:30 PM',t2:'PUJ → MIA: choose a Thursday flight that arrives by 7:30 PM and allows time for U.S. immigration',t3:'Drive FLL area → MIA; arrive by 8:00 PM Thursday',shared:'Book the Thursday MIA → GIG overnight that is operating that date',summary:'Yes—Traveler 1 and Traveler 2 need new Thursday-date flights. Flight numbers and times cannot be assumed from Wednesday until they are live-checked.'},
 fri:{departure:'Friday, Sep 25',arrival:'Saturday, Sep 26 · morning',feeder:'Re-price all three feeder trips for Friday',t1:'CLE → MIA: choose a Friday flight that arrives by 7:30 PM',t2:'PUJ → MIA: choose a Friday flight that arrives by 7:30 PM and allows time for U.S. immigration',t3:'Drive FLL area → MIA; arrive by 8:00 PM Friday',shared:'Book the Friday MIA → GIG overnight that is operating that date',summary:'Yes—every traveler’s date changes. This option leaves only Saturday to land, settle in and rest before the Sunday game.'}
} as const;

export default function TripBuilder(){
 const [flight,setFlight]=useState<'wed'|'thu'|'fri'>('wed'); const [picked,setPicked]=useState<string[]>(['christ','sugar','game']);
 const selectedPlan=flightPlans[flight];
 const toggle=(id:string)=>setPicked(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]);
 const recommendations=useMemo(()=>{const score={santa:0,copa:0,barra:0}; activities.forEach(a=>{if(picked.includes(a[0]))score[a[3]]+=1});return (Object.entries(score) as [keyof typeof stays,number][]).sort((a,b)=>b[1]-a[1]).filter(x=>x[1]>0);},[picked]);
 return <section className="builder" id="planner" aria-labelledby="builder-heading"><div className="section-heading"><p className="eyebrow">Build your trip in order</p><h2 id="builder-heading">Flight → fun → perfect stay</h2><p>Answer only what matters. Your Airbnb suggestions update as you choose activities.</p></div>
 <div className="builder-step"><span>1</span><div><p className="eyebrow">The one decision that sets the whole trip</p><h3>What matters most to your group?</h3><p>Pick the outcome you want. The first choice is the clear best fit for this itinerary.</p><div className="flight-options flight-cards"><label className={flight==='wed'?'selected':''}><input type="radio" checked={flight==='wed'} onChange={()=>setFlight('wed')}/><strong>I want the best overall Rio trip</strong><small><b>Choose Wednesday.</b> All three meet at MIA, fly overnight, and arrive GIG Thu Sep 24 at 8:20 AM with the full trip ahead.</small></label><label className={flight==='thu'?'selected':''}><input type="radio" checked={flight==='thu'} onChange={()=>setFlight('thu')}/><strong>I need one more preparation day</strong><small><b>Choose Thursday.</b> Re-book the feeder flights for Thursday; you arrive Friday morning and give up one full Rio day.</small></label><label className={flight==='fri'?'selected':''}><input type="radio" checked={flight==='fri'} onChange={()=>setFlight('fri')}/><strong>Friday is the only possible departure</strong><small><b>Choose Friday.</b> Re-book the feeder flights for Friday; you arrive Saturday morning with very little recovery time before the Sunday game.</small></label></div><div className="traveler-grid"><div><strong>Traveler 1 · Cleveland (CLE)</strong><small>{selectedPlan.t1}</small></div><div><strong>Traveler 2 · Punta Cana (PUJ)</strong><small>{selectedPlan.t2}</small></div><div><strong>Traveler 3 · Fort Lauderdale (FLL)</strong><small>{selectedPlan.t3}</small></div></div><p className="flight-summary"><strong>{selectedPlan.departure} departure → {selectedPlan.arrival} arrival.</strong> {selectedPlan.feeder}. {selectedPlan.summary} Reconfirm schedules and seats before purchase.</p></div></div>
 <div className="flight-impact"><span>What this choice means</span><h4>{flight==='wed'?'Recommended: arrive Thursday morning with the full trip ahead':flight==='thu'?'Backup: arrive Friday morning':'Least time: arrive Saturday morning'}</h4><p>{selectedPlan.summary} This is an overnight international flight, so choose lie-flat pods/business seats if possible: they make the first day much easier.</p><ul><li><strong>Shared flight:</strong> {selectedPlan.shared}.</li><li><strong>Seat goal:</strong> lie-flat business pods; choose seats together or near each other.</li><li><strong>Next step:</strong> {flight==='wed'?'pre-book the GIG meet-and-greet for 8:20 AM Thursday.':'live-check and book each traveler’s date-specific feeder flight before buying the group overnight ticket.'}</li></ul></div>
 <div className="builder-step"><span>2</span><div><h3>Choose the experiences you care about</h3><p>Pick as many or few as you want. These choices guide the stay recommendation.</p><div className="activity-choices">{activities.map(a=><label key={a[0]} className={picked.includes(a[0])?'selected':''}><input type="checkbox" checked={picked.includes(a[0])} onChange={()=>toggle(a[0])}/><strong>{a[1]}</strong><small>{a[2]}</small></label>)}</div></div></div>
 <div className="builder-step"><span>3</span><div><h3>Your stay suggestions</h3>{recommendations.length===0?<p className="empty">Pick at least one experience to see a suggested area.</p>:<div className="recommendations">{recommendations.slice(0,2).map(([area,score],index)=><div className="recommendation" key={area}><span>{index===0?'Best match':'Also consider'} · {score} selected activity{score>1?'ies':'y'} nearby</span><h4>{area==='santa'?'Santa Teresa':area==='copa'?'Copacabana':'Nature / private villa'}</h4>{stays[area].map((s,i)=><p key={s[0]}><a className="stay-map-link" href={'/guide.html?stay='+mapIds[area][i]} target="_blank" rel="noreferrer"><strong>{s[0]}</strong><br/>{s[2]}<br/><small>Open this Airbnb on the map ↗</small></a></p>)}</div>)}</div>}<a className="button button-primary map-button" href="/guide.html" target="_blank" rel="noreferrer">Open the interactive map <span>↗</span></a><p className="map-note">The full map opens in a new tab with every stay, distance, cost and booking link.</p></div></div>
 </section>;
}
