'use client';
import { useMemo, useState } from 'react';

const activities=[['christ','Christ by train','Iconic first-time Rio view','santa'],['sugar','Sugarloaf at sunset','Cable car + bay panorama','copa'],['beach','Ipanema / beach day','Easy, flexible beach time','copa'],['shopping','Mall shopping + luxury boutiques','Shopping Leblon, VillageMall and beach-neighborhood style','copa'],['samba','Samba + Santa Teresa','Music, food and cultural energy','santa'],['game','Maracanã game','Sunday’s fixed main event','santa'],['forest','Tijuca Forest','Nature and movement','barra'],['africa','Little Africa','Afro-Brazilian history and samba roots','santa']] as const;
const mapIds={santa:['harbourside','stpool','vintage'],copa:['rio001','adv001','panoramic'],barra:['pepe','castle','oasis']} as const;
const stays={santa:[['Harbourside 6-bedroom villa','Santa Teresa','Best overall for game day, Lapa and history.'],['Santa Teresa house with pool','Santa Teresa','Large-group base near Centro.'],['Vintage Chic Villa','Santa Teresa','Historic character and central access.']],copa:[['Rio001 beachfront penthouse','Copacabana','Best beach access with a lively base.'],['ADV001 oceanfront penthouse','Copacabana','Oceanfront pool and iconic location.'],['Copacabana Panoramic Penthouse','Copacabana','Classic Rio position and beach convenience.']],barra:[['Oceanfront penthouse with private pool','Barra / Praia do Pepe','Best secluded, celebrity-style beach feel.'],['A Castle in Rio — waterfall villa','Itanhangá','Best for a dramatic private escape.'],['Oasis in Freguesia','Freguesia','Best amenity value, with longer transfers.']]} as const;
const flightPlans={
 wed:{departure:'Wednesday, Sep 23',arrival:'Thursday, Sep 24 · 8:20 AM',feeder:'Meet at MIA Terminal D check-in at 8:00 PM',t1:'AA2887 · CLE 6:19 AM → MIA 9:15 AM',t2:'AA2419 · PUJ 1:44 PM → MIA 4:18 PM',t3:'Drive FLL area → MIA Terminal D; arrive by 8:00 PM',shared:'AA905 · MIA 11:00 PM → GIG 8:20 AM',summary:'This is the verified group plan. AA2638 does not operate Wednesday, so Traveler 2 uses AA2419. Everyone checks in and boards AA905 together.'},
 thu:{departure:'Thursday, Sep 24',arrival:'Friday, Sep 25 · 8:20 AM',feeder:'Meet at MIA Terminal D check-in at 8:00 PM Thursday',t1:'AA2887 · CLE 6:19 AM → MIA 9:15 AM',t2:'AA2638 · PUJ 12:01 PM → MIA 2:35 PM',t3:'Drive FLL area → MIA Terminal D; arrive by 8:00 PM Thursday',shared:'AA905 · MIA 11:00 PM → GIG 8:20 AM',summary:'All three can still leave together, but this gives up Thursday in Rio. Traveler 2 must use the Thursday-running AA2638 and clear U.S. immigration before the group meeting.'},
 fri:{departure:'Friday, Sep 25',arrival:'Saturday, Sep 26 · 8:20 AM',feeder:'Meet at MIA Terminal D check-in at 8:00 PM Friday',t1:'AA2887 · CLE 6:19 AM → MIA 9:15 AM',t2:'AA2638 · PUJ 12:01 PM → MIA 2:35 PM',t3:'Drive FLL area → MIA Terminal D; arrive by 8:00 PM Friday',shared:'AA905 · MIA 11:00 PM → GIG 8:20 AM',summary:'All three can still leave together, but the group lands Saturday with only one recovery day before Sunday’s game. Keep Saturday intentionally light.'}
} as const;
const returnPlans={
 mon:{label:'Leave Monday night',detail:'AA904 · GIG Mon Sep 28, 10:10 PM → MIA Tue Sep 29, 5:45 AM',impact:'This keeps the Sunday game but removes the relaxed Monday / Little Africa day. Use Monday only to pack, have a late checkout and go to the airport together.',cle:'AA363 · MIA Tue 8:46 PM → CLE 11:46 PM',dtw:'AA2649 · MIA Tue 7:46 PM → DTW',fll:'Private car MIA → Fort Lauderdale after group arrival'},
 tue:{label:'Leave Tuesday night',detail:'AA904 · GIG Tue Sep 29, 10:10 PM → MIA Wed Sep 30, 5:45 AM',impact:'Best overall rhythm: Monday stays open for Little Africa, beach time or recovery, then the group leaves together Tuesday night.',cle:'AA363 · MIA Wed 8:46 PM → CLE 11:46 PM',dtw:'AA2649 · MIA Wed 7:46 PM → DTW',fll:'Private car MIA → Fort Lauderdale after group arrival'}
} as const;

export default function TripBuilder(){
 const [flight,setFlight]=useState<'wed'|'thu'|'fri'>('wed'); const [returnDay,setReturnDay]=useState<'mon'|'tue'>('tue'); const [picked,setPicked]=useState<string[]>(['christ','sugar','game']);
 const selectedPlan=flightPlans[flight];
 const selectedReturn=returnPlans[returnDay];
 const toggle=(id:string)=>setPicked(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]);
 const recommendations=useMemo(()=>{const score={santa:0,copa:0,barra:0}; activities.forEach(a=>{if(picked.includes(a[0]))score[a[3]]+=1});return (Object.entries(score) as [keyof typeof stays,number][]).sort((a,b)=>b[1]-a[1]).filter(x=>x[1]>0);},[picked]);
 return <section className="builder" id="planner" aria-labelledby="builder-heading"><div className="section-heading"><p className="eyebrow">Build your trip in order</p><h2 id="builder-heading">Flight → fun → perfect stay</h2><p>Answer only what matters. Your Airbnb suggestions update as you choose activities.</p></div>
 <div className="builder-step"><span>1</span><div><p className="eyebrow">The one decision that sets the whole trip</p><h3>What matters most to your group?</h3><p>Pick the outcome you want. The first choice is the clear best fit for this itinerary.</p><div className="flight-options flight-cards"><label className={flight==='wed'?'selected':''}><input type="radio" checked={flight==='wed'} onChange={()=>setFlight('wed')}/><strong>I want the best overall Rio trip</strong><small><b>Choose Wednesday.</b> All three meet at MIA, fly overnight, and arrive GIG Thu Sep 24 at 8:20 AM with the full trip ahead.</small></label><label className={flight==='thu'?'selected':''}><input type="radio" checked={flight==='thu'} onChange={()=>setFlight('thu')}/><strong>I need one more preparation day</strong><small><b>Choose Thursday.</b> Re-book the feeder flights for Thursday; you arrive Friday morning and give up one full Rio day.</small></label><label className={flight==='fri'?'selected':''}><input type="radio" checked={flight==='fri'} onChange={()=>setFlight('fri')}/><strong>Friday is the only possible departure</strong><small><b>Choose Friday.</b> Re-book the feeder flights for Friday; you arrive Saturday morning with very little recovery time before the Sunday game.</small></label></div><h4>When does the group leave Rio?</h4><div className="flight-options flight-cards"><label className={returnDay==='mon'?'selected':''}><input type="radio" checked={returnDay==='mon'} onChange={()=>setReturnDay('mon')}/><strong>Leave Monday night</strong><small>Keep the Sunday game, but Monday becomes pack, rest and airport only.</small></label><label className={returnDay==='tue'?'selected':''}><input type="radio" checked={returnDay==='tue'} onChange={()=>setReturnDay('tue')}/><strong>Leave Tuesday night</strong><small><b>Recommended.</b> Keep the easy Monday cultural / recovery day, then leave together Tuesday night.</small></label></div><h4>Your live group routing</h4><div className="traveler-grid"><div><strong>Traveler 1 · Cleveland (CLE)</strong><small><b>To MIA:</b> {selectedPlan.t1}<br/><b>Home:</b> {selectedReturn.cle}</small></div><div><strong>Traveler 2 · Punta Cana (PUJ)</strong><small><b>To MIA:</b> {selectedPlan.t2}<br/><b>Home:</b> {selectedReturn.dtw}</small></div><div><strong>Traveler 3 · Fort Lauderdale (FLL)</strong><small><b>To MIA:</b> {selectedPlan.t3}<br/><b>Home:</b> {selectedReturn.fll}</small></div></div><p className="flight-summary"><strong>{selectedPlan.departure} departure → {selectedPlan.arrival} arrival.</strong> {selectedPlan.feeder}. {selectedPlan.summary} <strong>Return:</strong> {selectedReturn.detail}. {selectedReturn.impact} Reconfirm schedules and seats before purchase.</p></div></div>
 <div className="flight-impact"><span>What this choice means</span><h4>{flight==='wed'?'Recommended: arrive Thursday morning with the full trip ahead':flight==='thu'?'Backup: arrive Friday morning':'Least time: arrive Saturday morning'}</h4><p>{selectedPlan.summary} {selectedReturn.impact} This is an overnight international flight, so choose lie-flat pods/business seats if possible: they make the first day much easier.</p><ul><li><strong>Shared flight:</strong> {selectedPlan.shared}.</li><li><strong>Group rule:</strong> nobody clears check-in or boards the international flight alone; meet at Terminal D at 8:00 PM, then go through security together.</li><li><strong>Return together:</strong> {selectedReturn.detail}. Clear U.S. immigration and baggage together; the group trip ends only once everyone reaches the public arrivals area.</li><li><strong>Then split from MIA:</strong> Traveler 1: {selectedReturn.cle}; Traveler 2: {selectedReturn.dtw}; Traveler 3: {selectedReturn.fll}.</li><li><strong>Next step:</strong> book the three positioning segments and AA905/AA904 as one coordinated itinerary; do not book the Cleveland or Detroit flight before the shared group-return details are confirmed.</li></ul></div>
 <div className="builder-step"><span>2</span><div><h3>Choose the experiences you care about</h3><p>Pick as many or few as you want. These choices guide the stay recommendation.</p><div className="activity-choices">{activities.map(a=><label key={a[0]} className={picked.includes(a[0])?'selected':''}><input type="checkbox" checked={picked.includes(a[0])} onChange={()=>toggle(a[0])}/><strong>{a[1]}</strong><small>{a[2]}</small></label>)}</div></div></div>
 <div className="builder-step"><span>3</span><div><h3>Your stay suggestions</h3>{recommendations.length===0?<p className="empty">Pick at least one experience to see a suggested area.</p>:<div className="recommendations">{recommendations.slice(0,2).map(([area,score],index)=><div className="recommendation" key={area}><span>{index===0?'Best match':'Also consider'} · {score} selected activity{score>1?'ies':'y'} nearby</span><h4>{area==='santa'?'Santa Teresa':area==='copa'?'Copacabana':'Nature / private villa'}</h4>{stays[area].map((s,i)=>{const query=new URLSearchParams({stay:mapIds[area][i],departure:flight,returnDay,activities:picked.join(',')});return <p key={s[0]}><a className="stay-map-link" href={'/guide.html?'+query.toString()} target="_blank" rel="noreferrer"><strong>{s[0]}</strong><br/>{s[2]}<br/><small>Open your selected stay on the map ↗</small></a></p>})}</div>)}</div>}<a className="button button-primary map-button" href={'/guide.html?'+new URLSearchParams({departure:flight,returnDay,activities:picked.join(',')}).toString()} target="_blank" rel="noreferrer">Open your interactive map <span>↗</span></a><p className="map-note">The map opens with your selected travel dates, activities and—when chosen—Airbnb highlighted.</p></div></div>
 </section>;
}
