'use client';
import { useMemo, useState } from 'react';

const activities=[['christ','Christ by train','Iconic first-time Rio view','santa'],['sugar','Sugarloaf at sunset','Cable car + bay panorama','copa'],['beach','Ipanema / beach day','Easy, flexible beach time','copa'],['shopping','Mall shopping + luxury boutiques','Shopping Leblon, VillageMall and beach-neighborhood style','copa'],['samba','Samba + Santa Teresa','Music, food and cultural energy','santa'],['game','Maracanã game','Sunday’s fixed main event','santa'],['forest','Tijuca Forest','Nature and movement','barra'],['africa','Little Africa','Afro-Brazilian history and samba roots','santa']] as const;
const mapIds={santa:['harbourside','stpool','vintage'],copa:['rio001','adv001','panoramic'],barra:['pepe','castle','oasis']} as const;
const stays={santa:[['Harbourside 6-bedroom villa','Santa Teresa','Best overall for game day, Lapa and history.'],['Santa Teresa house with pool','Santa Teresa','Large-group base near Centro.'],['Vintage Chic Villa','Santa Teresa','Historic character and central access.']],copa:[['Rio001 beachfront penthouse','Copacabana','Best beach access with a lively base.'],['ADV001 oceanfront penthouse','Copacabana','Oceanfront pool and iconic location.'],['Copacabana Panoramic Penthouse','Copacabana','Classic Rio position and beach convenience.']],barra:[['Oceanfront penthouse with private pool','Barra / Praia do Pepe','Best secluded, celebrity-style beach feel.'],['A Castle in Rio — waterfall villa','Itanhangá','Best for a dramatic private escape.'],['Oasis in Freguesia','Freguesia','Best amenity value, with longer transfers.']]} as const;

export default function TripBuilder(){
 const [flight,setFlight]=useState('wed'); const [picked,setPicked]=useState<string[]>(['christ','sugar','game']);
 const toggle=(id:string)=>setPicked(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]);
 const recommendations=useMemo(()=>{const score={santa:0,copa:0,barra:0}; activities.forEach(a=>{if(picked.includes(a[0]))score[a[3]]+=1});return (Object.entries(score) as [keyof typeof stays,number][]).sort((a,b)=>b[1]-a[1]).filter(x=>x[1]>0);},[picked]);
 return <section className="builder" id="planner" aria-labelledby="builder-heading"><div className="section-heading"><p className="eyebrow">Build your trip in order</p><h2 id="builder-heading">Flight → fun → perfect stay</h2><p>Answer only what matters. Your Airbnb suggestions update as you choose activities.</p></div>
 <div className="builder-step"><span>1</span><div><p className="eyebrow">The one decision that sets the whole trip</p><h3>What matters most to your group?</h3><p>Pick the outcome you want. The first choice is the clear best fit for this itinerary.</p><div className="flight-options flight-cards"><label className={flight==='wed'?'selected':''}><input type="radio" checked={flight==='wed'} onChange={()=>setFlight('wed')}/><strong>I want the best overall Rio trip</strong><small><b>Choose Wednesday.</b> All three meet at MIA, fly overnight, and arrive GIG Thu Sep 24 at 8:20 AM with the full trip ahead.</small></label><label className={flight==='thu'?'selected':''}><input type="radio" checked={flight==='thu'} onChange={()=>setFlight('thu')}/><strong>I need one more preparation day</strong><small><b>Choose Thursday.</b> Same group flight idea, but you give up one full Rio day and arrive Friday morning.</small></label><label className={flight==='fri'?'selected':''}><input type="radio" checked={flight==='fri'} onChange={()=>setFlight('fri')}/><strong>Friday is the only possible departure</strong><small><b>Choose Friday.</b> You arrive Saturday morning with very little recovery time before the Sunday game.</small></label></div><div className="traveler-grid"><div><strong>Traveler 1 · Cleveland (CLE)</strong><small>AA2887: CLE 6:25 AM → MIA 9:20 AM</small></div><div><strong>Traveler 2 · Punta Cana (PUJ)</strong><small>AA2638: PUJ 12:02 PM → MIA 2:39 PM</small></div><div><strong>Traveler 3 · Fort Lauderdale (FLL)</strong><small>Drive to MIA; arrive by 8:00 PM</small></div></div><p className="flight-summary"><strong>Why Wednesday wins:</strong> everyone meets at MIA, sleeps on the same lie-flat overnight flight instead of paying for a Miami hotel, and arrives in Rio with time to settle in. Reconfirm schedules and seats before purchase.</p></div></div>
 <div className="flight-impact"><span>What this choice means</span>{flight==='wed'?<><h4>Recommended: arrive Thursday morning with the full trip ahead</h4><p>You get the most time in Rio and can settle in before the planned activities. This is an overnight international flight, so choose lie-flat pods/business seats if possible: they make the first day much easier.</p><ul><li><strong>Book together:</strong> AA905 MIA → GIG, 10:55 PM–8:20 AM.</li><li><strong>Seat goal:</strong> lie-flat business pods; choose seats together or near each other.</li><li><strong>Next step:</strong> pre-book the GIG meet-and-greet for 8:20 AM Thursday.</li></ul></>:flight==='thu'?<><h4>Backup: arrive Friday morning</h4><p>This preserves the group flight plan but removes one Rio day. Keep Thursday free at home and move the first full sightseeing day later.</p><ul><li><strong>Same flight type:</strong> overnight MIA → GIG; lie-flat seats are still the easiest choice.</li><li><strong>Trip effect:</strong> less recovery time before the weekend.</li><li><strong>Next step:</strong> shift the private airport pickup to Friday morning.</li></ul></>:<><h4>Least time: arrive Saturday morning</h4><p>Choose this only if Friday is required. The group arrives with very little time to settle before the Sunday game.</p><ul><li><strong>Same flight type:</strong> overnight MIA → GIG.</li><li><strong>Trip effect:</strong> skip a relaxed arrival day and keep Saturday very light.</li><li><strong>Next step:</strong> book a flexible, direct airport transfer and simple dinner.</li></ul></>}</div>
 <div className="builder-step"><span>2</span><div><h3>Choose the experiences you care about</h3><p>Pick as many or few as you want. These choices guide the stay recommendation.</p><div className="activity-choices">{activities.map(a=><label key={a[0]} className={picked.includes(a[0])?'selected':''}><input type="checkbox" checked={picked.includes(a[0])} onChange={()=>toggle(a[0])}/><strong>{a[1]}</strong><small>{a[2]}</small></label>)}</div></div></div>
 <div className="builder-step"><span>3</span><div><h3>Your stay suggestions</h3>{recommendations.length===0?<p className="empty">Pick at least one experience to see a suggested area.</p>:<div className="recommendations">{recommendations.slice(0,2).map(([area,score],index)=><div className="recommendation" key={area}><span>{index===0?'Best match':'Also consider'} · {score} selected activity{score>1?'ies':'y'} nearby</span><h4>{area==='santa'?'Santa Teresa':area==='copa'?'Copacabana':'Nature / private villa'}</h4>{stays[area].map((s,i)=><p key={s[0]}><a className="stay-map-link" href={'/guide.html?stay='+mapIds[area][i]} target="_blank" rel="noreferrer"><strong>{s[0]}</strong><br/>{s[2]}<br/><small>Open this Airbnb on the map ↗</small></a></p>)}</div>)}</div>}<a className="button button-primary map-button" href="/guide.html" target="_blank" rel="noreferrer">Open the interactive map <span>↗</span></a><p className="map-note">The full map opens in a new tab with every stay, distance, cost and booking link.</p></div></div>
 </section>;
}
